#!/bin/bash

while getopts u:p:f: flag 
do
    case "${flag}" in
    u) user=${OPTARG};;
    p) pass=${OPTARG};;
    f) file=${OPTARG};;
  esac
done

#Authenticate to obtain access_token
token=$(curl -X POST "https://api.crowdstrike.com/oauth2/token" -H "accept: application/json" -H "Content-Type: application/x-www-form-urlencoded" -d "client_id=$user&client_secret=$pass" | grep -i access_token | awk {'print $2'} | sed 's/["{,]//g')

audit=$(for i in `cat $file`; do curl -s -X GET "https://api.crowdstrike.com/malquery/entities/metadata/v1?ids=${i}" -H 'Authorization: Bearer '${token}'' -H 'Accept: application/json' |grep -B 2 -i label | awk '!/filesize/'| sed 's/.*://' | sed 's/[,"]//g'; done)

malware=$(echo "$audit" | grep -B1 -i malware | sed 's/malware//' | sed 's/--//')

malware_list=$(for m in $malware; do echo $m is Malware; done)

echo "$malware_list"
